fix failure when building cache.img
Add back config:

TARGET_USERIMAGES_USE_EXT4 := true

Didn't figure out why, since we already have
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
Build system should be able to figure out TARGET_USERIMAGES_USE_EXT4 is
true.

Also, didn't know why cache.img will need userimage's filesystem type to be
successful.

Will work on that later..

 82% 46565/56225] Target cache fs image:
out/target/product/poplar/cache.img
FAILED: out/target/product/poplar/cache.img
/bin/bash -c "(mkdir -p out/target/product/poplar/cache ) && (mkdir -p
out/target/product/poplar/obj/PACKAGING/cache_intermediates && rm -rf
out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
) && (echo \"ext_mkuserimg=mkuserimg.sh\" >>
out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
) && (echo \"system_size=1073741312\" >>
out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
) && (echo \"system_fs_type=ext4\" >>
out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
) && (echo \"userdata_fs_type=ext4\" >>
out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
) && (echo \"userdata_size=5456789504\" >>
out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
) && (echo \"cache_fs_type=ext4\" >>
out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
) && (echo \"cache_size=1073741312\" >>
out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
) && (echo \"extfs_sparse_flag=-s\" >>
out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
) && (echo \"squashfs_sparse_flag=-s\" >>
out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
) && (echo
\"selinux_fc=out/target/product/poplar/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin\"
>>  out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
>>  ) && (echo \"skip_fsck=true\" >>
>>  out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
>>  ) && (PATH=\$PATH ./build/tools/releasetools/build_image.py
>>  out/target/product/poplar/cache
>>  out/target/product/poplar/obj/PACKAGING/cache_intermediates/cache_image_info.txt
>>  out/target/product/poplar/cache.img out/target/product/poplar/system
>>  ) && (size=\$(for i in out/target/product/poplar/cache.img; do stat
>>  --format \"%s\" \"\$i\" | tr -d '\\n'; echo +; done; echo 0);
>>  total=\$(( \$( echo \"\$size\" ) )); printname=\$(echo -n
>>  \"out/target/product/poplar/cache.img\" | tr \" \" +);
>>  img_blocksize=2112; twoblocks=\$((img_blocksize * 2));
>>  onepct=\$(((((1107294144 / 100) - 1) / img_blocksize + 1) *
>>  img_blocksize)); reserve=\$((twoblocks > onepct ? twoblocks :
>>  onepct)); maxsize=\$((1107294144 - reserve)); echo \"\$printname
>>  maxsize=\$maxsize blocksize=\$img_blocksize total=\$total
>>  reserve=\$reserve\"; if [ \"\$total\" -gt \"\$maxsize\" ]; then echo
>>  \"error: \$printname too large (\$total > [1107294144 -
>>  \$reserve])\"; false; elif [ \"\$total\" -gt \$((maxsize - 32768))
>>  ]; then echo \"WARNING: \$printname approaching size limit (\$total
>>  now; limit \$maxsize)\"; fi )"
Running:  mkuserimg.sh -s out/target/product/poplar/cache
out/target/product/poplar/cache.img ext4 cache 1073741312 -D
out/target/product/poplar/system -L cache
out/target/product/poplar/obj/ETC/file_contexts.bin_intermediates/file_contexts.bin
Traceback (most recent call last):
  File "./build/tools/releasetools/build_image.py", line 755, in
<module>
    main(sys.argv[1:])
  File "./build/tools/releasetools/build_image.py", line 748, in main
    if not BuildImage(in_dir, image_properties, out_file, target_out):
  File "./build/tools/releasetools/build_image.py", line 501, in
BuildImage
    (ext4fs_output, exit_code) = RunCommand(build_command)
  File "./build/tools/releasetools/build_image.py", line 48, in
RunCommand
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE,
stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Signed-off-by: Bin Chen <bin.chen@linaro.org>